# Generated by Django 2.2.5 on 2019-09-25 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190925_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 21, 43, 59, 342475), verbose_name='date published'),
        ),
    ]
