# Generated by Django 2.2.5 on 2019-09-25 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190925_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 22, 1, 31, 543192), verbose_name='date published'),
        ),
    ]
