# Generated by Django 2.1.1 on 2020-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200311_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='wiki_article_body',
            field=models.TextField(),
        ),
    ]
