# Generated by Django 2.1.1 on 2020-03-12 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200311_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiarticle',
            name='wiki_article_body',
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='body',
            field=models.TextField(default='body'),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='chapter_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 18, 2, 55, 912203)),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='subchapter_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='title_short',
            field=models.CharField(default='title_short', max_length=50),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
