# Generated by Django 2.1.1 on 2020-03-13 09:42

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200312_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='body',
            field=tinymce.models.HTMLField(default='body'),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 9, 42, 34, 808015)),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='title_short',
            field=models.CharField(default='title_short', max_length=27),
        ),
    ]
