# Generated by Django 2.1.1 on 2020-03-13 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200313_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 13, 13, 4, 26, 311699)),
        ),
    ]
