# Generated by Django 2.1.1 on 2020-04-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200409_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-date']},
        ),
    ]
