# Generated by Django 2.1.1 on 2020-05-02 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200502_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='current_customers',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 21, 28, 58, 273324)),
        ),
    ]
