# Generated by Django 2.1.1 on 2020-05-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200504_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancy',
            name='capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='person_count',
            field=models.IntegerField(default=2),
        ),
    ]
