# Generated by Django 2.1.1 on 2020-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200504_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='person_count',
            field=models.IntegerField(default=1),
        ),
    ]
