# Generated by Django 3.0.6 on 2020-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200529_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancy',
            name='direction',
            field=models.IntegerField(default=1),
        ),
    ]
