# Generated by Django 2.1.1 on 2020-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200529_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_threshold', models.IntegerField(default=10)),
            ],
        ),
    ]
